In [2]:
import pandas as pd
import matplotlib.pyplot as plt
d=pd.read_csv('/content/Real estate (1) (1).csv')
print(d)
x=d.iloc[:,0:1]
y=d.iloc[:,1:2]
print(x,y)
from sklearn.model_selection import train_test_split
X_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.10,random_state=5)
print(X_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
import numpy as np
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.linear_model import Lasso 
model_lasso= Lasso(alpha=0.01)
model_lasso.fit(x,y) 
pred_train_lasso= model_lasso.predict(x_test)
print(mean_squared_error(y_test,pred_train_lasso))
import numpy as np
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.linear_model import Lasso 
model_lasso= Lasso(alpha=0.01)
model_lasso.fit(x,y) 
pred_train_lasso= model_lasso.predict(x_test)
print(mean_squared_error(y_test,pred_train_lasso))

      No  X1 transaction date  X2 house age  \
0      1             2012.917          32.0   
1      2             2012.917          19.5   
2      3             2013.583          13.3   
3      4             2013.500          13.3   
4      5             2012.833           5.0   
..   ...                  ...           ...   
409  410             2013.000          13.7   
410  411             2012.667           5.6   
411  412             2013.250          18.8   
412  413             2013.000           8.1   
413  414             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 3

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('/content/Real estate (1) (1).csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values
print(X)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], 
remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
b1=1
b0=1
summation = 0 
n = len(y)
for i in range (0,n): 
    y_bar =(b1*y[i])+b0
    dif =(X[i])-(y_bar) 
    squared_difference = dif*dif 
    summation = summation + squared_difference 
MSE = summation/n 
print("The Mean Square Error is: ",MSE)

[[2012.917     32.        84.87882   10.        24.98298  121.54024]
 [2012.917     19.5      306.5947     9.        24.98034  121.53951]
 [2013.583     13.3      561.9845     5.        24.98746  121.54391]
 ...
 [2013.25      18.8      390.9696     7.        24.97923  121.53986]
 [2013.         8.1      104.8101     5.        24.96674  121.54067]
 [2013.5        6.5       90.45606    9.        24.97433  121.5431 ]]
[[  0.        0.        0.      ...  84.87882  24.98298 121.54024]
 [  0.        0.        0.      ... 306.5947   24.98034 121.53951]
 [  0.        0.        0.      ... 561.9845   24.98746 121.54391]
 ...
 [  0.        0.        0.      ... 390.9696   24.97923 121.53986]
 [  0.        0.        0.      ... 104.8101   24.96674 121.54067]
 [  0.        0.        0.      ...  90.45606  24.97433 121.5431 ]]
[[43.53 45.3 ]
 [15.51 14.4 ]
 [44.89 46.  ]
 [15.4  15.6 ]
 [46.05 50.2 ]
 [41.44 38.1 ]
 [38.41 48.5 ]
 [36.79 41.4 ]
 [47.44 51.6 ]
 [46.96 40.1 ]
 [43.65 42.  ]
 [41.35